//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllVehicleExpense
    {
        public long iAllVehicleExpenseID { get; set; }
        public Nullable<int> iPurchaseInvoiceID { get; set; }
        public int iExpenseID { get; set; }
        public Nullable<int> iExpenseAmount { get; set; }
        public Nullable<int> iTotalExpenseAmounrt { get; set; }
    }
}
