//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCompany
    {
        public int iCompanyID { get; set; }
        public string strCompanyName { get; set; }
        public string strArea { get; set; }
        public Nullable<int> iCountry { get; set; }
        public Nullable<int> iCity { get; set; }
        public string strEmailID { get; set; }
        public string strWebsites { get; set; }
        public Nullable<int> iPhoneNumber { get; set; }
        public Nullable<int> iOfcPhoneNumber { get; set; }
        public string strAddress { get; set; }
    }
}
