//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLot
    {
        public long iLotID { get; set; }
        public string strLotName { get; set; }
        public string strFromDate { get; set; }
        public Nullable<System.DateTime> dtFromDate { get; set; }
        public string strToDate { get; set; }
        public Nullable<System.DateTime> dtToDate { get; set; }
        public string chLotType { get; set; }
    }
}
