//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MStaff
    {
        public int iStaffID { get; set; }
        public string strFirstName { get; set; }
        public string strMiddleName { get; set; }
        public string strLastName { get; set; }
        public string strNationalityAddress { get; set; }
        public Nullable<int> iNationality { get; set; }
        public Nullable<int> iNationalityContact { get; set; }
        public string strEmailID { get; set; }
        public Nullable<int> iIDNO { get; set; }
        public string strMISC { get; set; }
        public string strPassport { get; set; }
        public string strPassportExpiry { get; set; }
        public string strVisa { get; set; }
        public string strVisaExpiry { get; set; }
        public string strCurrentAddress { get; set; }
        public Nullable<int> iDesignation { get; set; }
        public Nullable<decimal> dmlSalary { get; set; }
        public string DOB { get; set; }
        public string DOJ { get; set; }
        public string strRemark { get; set; }
    }
}
