//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSupplier
    {
        public int iSupplierID { get; set; }
        public string strFirstName { get; set; }
        public string strMiddleName { get; set; }
        public string strLastName { get; set; }
        public Nullable<int> iSupplierCategory { get; set; }
        public Nullable<int> iSupplierServiceType { get; set; }
        public string strEmailID { get; set; }
        public string iPhoneNumber { get; set; }
        public string strAddress { get; set; }
        public Nullable<int> iPincode { get; set; }
        public Nullable<int> iCurrency { get; set; }
        public string SupplierDate { get; set; }
        public string Password { get; set; }
        public string SupplierPhoto { get; set; }
        public string iPersonPhoneNumber { get; set; }
        public string strPersonEmailID { get; set; }
        public string strCompanyName { get; set; }
        public string strWebsites { get; set; }
        public string strPicName { get; set; }
    }
}
