//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperDetailsForImport
    {
        public long iPaperDetailsForImportID { get; set; }
        public Nullable<int> iVehicleID { get; set; }
        public Nullable<int> iDecNo { get; set; }
        public string strDecDate { get; set; }
        public Nullable<int> iImpDeposit { get; set; }
        public Nullable<int> iDuty { get; set; }
        public Nullable<int> iPaper { get; set; }
        public Nullable<int> iTotal { get; set; }
        public Nullable<int> iImpBalance { get; set; }
    }
}
