//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperDetailsForExport
    {
        public long iPaperDetailsForExportID { get; set; }
        public Nullable<int> iVehicleID { get; set; }
        public string strReceivingDate { get; set; }
        public string strSubmitDate { get; set; }
        public Nullable<int> iCustApproval { get; set; }
        public Nullable<decimal> dcmlDeduction { get; set; }
        public Nullable<decimal> dcmlFine { get; set; }
        public Nullable<decimal> dcmlMisc { get; set; }
        public Nullable<decimal> dcmlExportDeposit { get; set; }
        public Nullable<decimal> dcmlExportBalance { get; set; }
    }
}
