//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperDetailsForImport
    {
        public long iPaperDetailsForImportID { get; set; }
        public Nullable<int> iVehicleID { get; set; }
        public Nullable<int> iDecNo { get; set; }
        public string strDecDate { get; set; }
        public Nullable<decimal> dcmlImpDeposit { get; set; }
        public Nullable<decimal> dcmlDuty { get; set; }
        public Nullable<decimal> dcmlPaper { get; set; }
        public Nullable<decimal> dcmlTotal { get; set; }
        public Nullable<decimal> dcmlImpBalance { get; set; }
    }
}
