//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperDetailsForExport
    {
        public long iPaperDetailsForExportID { get; set; }
        public Nullable<int> iVehicleID { get; set; }
        public string strReceivingDate { get; set; }
        public string strSubmitDate { get; set; }
        public Nullable<int> iCustApproval { get; set; }
        public Nullable<int> iDeduction { get; set; }
        public Nullable<int> iFine { get; set; }
        public Nullable<int> iMisc { get; set; }
        public Nullable<int> iExportDeposit { get; set; }
        public Nullable<int> iExportBalance { get; set; }
    }
}
