//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPayment
    {
        public long iPaymentID { get; set; }
        public Nullable<long> iSaleID { get; set; }
        public Nullable<int> iCustomerID { get; set; }
        public string strPaymentDate { get; set; }
        public Nullable<System.DateTime> dtPaymentDate { get; set; }
        public Nullable<decimal> dmlPaidAmount { get; set; }
        public Nullable<decimal> dmlPrevBalance { get; set; }
        public Nullable<bool> ysnPaymentStatus { get; set; }
        public Nullable<int> iSalesInvoiceID { get; set; }
        public string strSalesInvoiceNo { get; set; }
    }
}
