//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuthorizedPages
    {
        public long id { get; set; }
        public long PageId { get; set; }
        public string PageName { get; set; }
        public int RoleId { get; set; }
        public long PageId { get; set; }
    }
}
