//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionInventoryDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPurchase
    {
        public TPurchase()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public long PurchaseID { get; set; }
        public Nullable<int> iPurchaseInvoiceNo { get; set; }
        public string strPurchaseInvoiceDate { get; set; }
        public string strSupplierName { get; set; }
        public string strMasterDecNo { get; set; }
        public string strBLNo { get; set; }
        public string strArrivalDate { get; set; }
        public string strInvoiceValue { get; set; }
        public string strPurchaseInvoiceNo { get; set; }
        public Nullable<System.DateTime> dtPurchaseInvoiceDate { get; set; }
        public Nullable<decimal> dcmlAED { get; set; }
        public Nullable<decimal> dcmlJYP { get; set; }
        public Nullable<decimal> dmlConversionRate { get; set; }
    
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
